/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sanke;

import java.awt.Color;
import java.awt.GridLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author joshu
 */
public class panel extends javax.swing.JFrame {

    //jlabel -> botones, txt
    JLabel[][] cuadriculaJuego;
    
    
    // hilos 
    private Thread hiloRepintar;
    
    
    //borde del tablero
    int izquierda = 0;
    int derecha = 10;
    
    
    
    //
    int x=1;
    int y=1;
    
    
    //posicion inical del snake
    int snakex = 5;
    int snakey = 5;
    
    //fruta
    int frutax = 1;
    int frutay = 1;
    
    
    // velocidad del sanke
    int velocidad = 2000;
    
    
    int contadorfrutas = 0;
    
    /**
     * Creates new form panel
     */
    public panel() {        
        initComponents();
        snakeGame();
    }

    
    
    public void snakeGame(){
        
        // visibilidad del panel
        this.jPanel1.setVisible(true);
        
        
        //matriz del juego
        cuadriculaJuego = new JLabel[10][10];
        
        
        
        // un doble for para manejar la matriz
        for (int i=0; i<cuadriculaJuego.length; i++){
            for(int j=0; j<cuadriculaJuego.length; j++){
                
                //poder crear un label en esa poscion
                cuadriculaJuego[i][j] = new JLabel();
                cuadriculaJuego[i][j].setOpaque(true);
                
                cuadriculaJuego[i][j].setBackground(Color.white);
                
                // posicion x y posicion y
                // tamanio de cada cuadro
                cuadriculaJuego[i][j].setBounds(x,y,50,50);  
                
                x= x + 51;
                this.jPanel1.add(cuadriculaJuego[i][j]);
            }
            y = y + 51;
            x=1;
        }
        
        // pintar el snake
        cuadriculaJuego[snakex][snakey].setBackground(Color.red);
        
        // 1,1 de color verde
        cuadriculaJuego[frutax][frutay].setBackground(Color.green);
        
        
        
        //arranque del hilo
        hiloRepintar = new Thread( () ->{
            this.mover();
        });    
        hiloRepintar.start();
        
    }
    
    
    
    // funcion de mover el snake
    public void mover(){
        while(true){
            snakey ++;
            
            //pintar
            cuadriculaJuego[snakex][snakey].setBackground(Color.red);
            
            //despintar
            cuadriculaJuego[snakex][snakey-1].setBackground(Color.white);
            
            // if 
            // el movimiento del snake
            // if el boton derecha se prociono snakey --;
            // el boton de hacia arriba fue procionad snakex --;
            
            
            //otro if para el choque
//            if ( cuadriculaJuego[snakex][snakey] || || ||){
//                System.out.println("hubo un choque");
//            }
                

            //if contarfutas >0
            // velocidad = velocidad - 0.30
            
            // if cuadriculaJuego[snakex][snakey] == cuadriculaJuego[frutax][frutay]
            // cuadriculaJuego[frutax][frutay]. colro blanco
            
            
            //velocidad es una espera 
            try {
                Thread.sleep(velocidad);
            } catch (InterruptedException ex) {
                Logger.getLogger(panel.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new panel().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
